### ISSUE TITLE
Camera not recognizing face

### ISSUE THREAD

**Issue by Clintvd** [nischi/MMM-Face-Reco-DNN#115]
I'm all new to Linux so i dont't always seem to see what i'm missing or doing wrong. Got everything installed properly ( I guess) pictures are loaded in but the camera doesn't seem to be functioning. I found this error while my MM was running.

[10.10.2022 17:30.28.214] [LOG]   [MMM-Face-Reco-DNN] loading encodings + face detector...
[10.10.2022 17:30.28.386] [ERROR] Whoops! There was an uncaught exception...
[10.10.2022 17:30.28.391] [ERROR] PythonShellError: FileNotFoundError: [Errno 2] No such file or directory: 'modules/MMM-Face-Reco-DNN/tools/encodings.pickle'
    at PythonShell.parseError (/home/clint/Documents/MagicMirror/modules/MMM-Face-Reco-DNN/node_modules/python-shell/index.js:246:21)
    at terminateIfNeeded (/home/clint/Documents/MagicMirror/modules/MMM-Face-Reco-DNN/node_modules/python-shell/index.js:129:32)
    at ChildProcess.<anonymous> (/home/clint/Documents/MagicMirror/modules/MMM-Face-Reco-DNN/node_modules/python-shell/index.js:121:13)
    at ChildProcess.emit (node:events:526:28)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
    ----- Python Traceback -----
    File "/home/clint/Documents/MagicMirror/modules/MMM-Face-Reco-DNN/tools/facerecognition.py", line 73, in <module>
      data = pickle.loads(open(args["encodings"], "rb").read()) {
  traceback: 'Traceback (most recent call last):\n' +
    '  File "/home/clint/Documents/MagicMirror/modules/MMM-Face-Reco-DNN/tools/facerecognition.py", line 73, in <module>\n' +
    '    data = pickle.loads(open(args["encodings"], "rb").read())\n' +
    "FileNotFoundError: [Errno 2] No such file or directory: 'modules/MMM-Face-Reco-DNN/tools/encodings.pickle'\n",
  executable: 'python3',
  options: null,
  script: 'modules/MMM-Face-Reco-DNN/tools/facerecognition.py',
  args: [
    '--cascade=modules/MMM-Face-Reco-DNN/tools/haarcascade_frontalface_default.xml',
    '--encodings=modules/MMM-Face-Reco-DNN/tools/encodings.pickle',
    '--usePiCamera=1',
    '--source=0',
    '--rotateCamera=0',
    '--method=dnn',
    '--detectionMethod=cnn',
    '--interval=1000',
    '--output=0',
    '--extendDataset=False',
    '--dataset=modules/MMM-Face-Reco-DNN/dataset/',
    '--tolerance=0.6'
  ],
  exitCode: 1

Thanks in advance

**Comment by nischi** [comment]
hi @Clintvd 
Thanks for using my module. it seems you have not create the encodings.pickle file. This need to be create with the python tool. that is needed to recognize known faces. 

[10.10.2022 17:30.28.391] [ERROR] PythonShellError: FileNotFoundError: [Errno 2] No such file or directory: 'modules/MMM-Face-Reco-DNN/tools/encodings.pickle'
