### ISSUE TITLE
 Error: Cannot find module 'python-shell'

### ISSUE THREAD

**Issue by ivanovd** [nischi/MMM-Face-Reco-DNN#4]
I get the following error when starting MagicMirror with the module configured:

```
WARNING! Could not load config file. Starting with default configuration. Error found: Error: Cannot find module 'python-shell'
App threw an error during load
Error: Cannot find module 'python-shell'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (internal/modules/cjs/loader.js:528:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Face-Reco-DNN/node_helper.js:10:23)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Face-Reco-DNN/node_helper.js:87:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
{ Error: Cannot find module 'python-shell'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (internal/modules/cjs/loader.js:528:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Face-Reco-DNN/node_helper.js:10:23)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Face-Reco-DNN/node_helper.js:87:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32) code: 'MODULE_NOT_FOUND' }
ATTENTION: default value of option force_s3tc_enable overridden by environment.
```

I have all dependencies installed and I have encoded the images.

**Comment by nischi** [comment]
Did you run `npm install`in my module folder to install python-shell?

**Comment by nischi** [comment]
I see i missed this part in my Documentation. Will add that.

**Comment by nischi** [comment]
Added to the documentation:

```sh
cd ~/MagicMirror/modules/
git clone https://github.com/nischi/MMM-Face-Reco-DNN.git
cd MMM-Face-Reco-DNN
npm install
```

**Comment by ivanovd** [comment]
Yep, that helped. Thanks for updating the docs. I have another issue but will open a separe ticket for it.

Thanks
