### ISSUE TITLE
PythonShellError: could not create component

### ISSUE THREAD

**Issue by Bl4CkGuuN** [nischi/MMM-Face-Reco-DNN#81]
Hello,

I tried to install the module today but get this error in the logs:

```
0|mm  | [22.01.2021 12:04.35.250] [ERROR]
0|mm  | Whoops! There was an uncaught exception...
0|mm  | [22.01.2021 12:04.35.265] [ERROR]
0|mm  | PythonShellError: mmal: mmal_vc_component_create: failed to create component 'vc.ril.camera' (1:ENOMEM)
0|mm  | mmal: mmal_component_create_core: could not create component 'vc.ril.camera' (1)
0|mm  | Traceback (most recent call last):
0|mm  |   File "/usr/lib/python3/dist-packages/picamera/camera.py", line 456, in _init_camera
0|mm  |     self._camera = mo.MMALCamera()
0|mm  |   File "/usr/lib/python3/dist-packages/picamera/mmalobj.py", line 2279, in __init__
0|mm  |     super(MMALCamera, self).__init__()
0|mm  |   File "/usr/lib/python3/dist-packages/picamera/mmalobj.py", line 633, in __init__
0|mm  |     prefix="Failed to create MMAL component %s" % self.component_type)
0|mm  |   File "/usr/lib/python3/dist-packages/picamera/exc.py", line 184, in mmal_check
0|mm  |     raise PiCameraMMALError(status, prefix)
0|mm  | picamera.exc.PiCameraMMALError: Failed to create MMAL component b'vc.ril.camera': Out of memory
0|mm  | During handling of the above exception, another exception occurred:
0|mm  | Traceback (most recent call last):
0|mm  |   File "modules/MMM-Face-Reco-DNN/tools/facerecognition.py", line 80, in <module>
0|mm  |     vs = VideoStream(usePiCamera=True, rotation=args["rotateCamera"]).start()
0|mm  |   File "/home/pi/.local/lib/python3.7/site-packages/imutils/video/videostream.py", line 18, in __init__
0|mm  |     framerate=framerate, **kwargs)
0|mm  |   File "/home/pi/.local/lib/python3.7/site-packages/imutils/video/pivideostream.py", line 10, in __init__
0|mm  |     self.camera = PiCamera()
0|mm  |   File "/usr/lib/python3/dist-packages/picamera/camera.py", line 431, in __init__
0|mm  |     self._init_camera(camera_num, stereo_mode, stereo_decimate)
0|mm  |   File "/usr/lib/python3/dist-packages/picamera/camera.py", line 460, in _init_camera
0|mm  |     "Camera is not enabled. Try running 'sudo raspi-config' "
0|mm  | picamera.exc.PiCameraError: Camera is not enabled. Try running 'sudo raspi-config' and ensure that the camera has been enabled.
0|mm  |     at PythonShell.parseError (/home/pi/MagicMirror/modules/MMM-Face-Reco-DNN/node_modules/python-shell/index.js:254:21)
0|mm  |     at terminateIfNeeded (/home/pi/MagicMirror/modules/MMM-Face-Reco-DNN/node_modules/python-shell/index.js:129:32)
0|mm  |     at ChildProcess.<anonymous> (/home/pi/MagicMirror/modules/MMM-Face-Reco-DNN/node_modules/python-shell/index.js:121:13)
0|mm  |     at ChildProcess.emit (events.js:210:5)
0|mm  |     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12) {
0|mm  |   executable: 'python3',
0|mm  |   options: null,
0|mm  |   script: 'modules/MMM-Face-Reco-DNN/tools/facerecognition.py',
0|mm  |   args: [
0|mm  |     '--cascade=modules/MMM-Face-Reco-DNN/tools/haarcascade_frontalface_default.xml',
0|mm  |     '--encodings=modules/MMM-Face-Reco-DNN/tools/encodings.pickle',
0|mm  |     '--usePiCamera=1',
0|mm  |     '--source=0',
0|mm  |     '--rotateCamera=1',
0|mm  |     '--method=dnn',
0|mm  |     '--detectionMethod=hog',
0|mm  |     '--interval=2000',
0|mm  |     '--output=0',
0|mm  |     '--extendDataset=True',
0|mm  |     '--dataset=modules/MMM-Face-Reco-DNN/dataset/',
0|mm  |     '--tolerance=0.6'
0|mm  |   ],
0|mm  |   exitCode: 1
0|mm  | }

```

Does someone have ideas? - The camera is enabled in the rapsi-config
I'm using a Raspberry 3 Model B

**Comment by Bl4CkGuuN** [comment]
My PI camera was a bit loose...

Tried it with `vcgencmd get_camera`
The output was `supported=1 detected=0` (detected should be 1)
