### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by JuhoJokine** [nischi/MMM-Face-Reco-DNN#83]
Hi

I did all the steps till the dataset part but i dont find folder named "dataset" from anywhere, am I supposed to make it by myself or have I done something incorrectly?

-Juho

**Comment by Bl4CkGuuN** [comment]
Yes, you have to create the dataset folder manually and then create a subfolder with every user including their pictures.

**Comment by JuhoJokine** [comment]
I did those and then tried to run the encode.py but got this:

Traceback (most recent call last):
  File "/home/pi/MagicMirror/modules/MMM-Face-Reco-DNN/tools/encode.py", line 5, in <module>
    from imutils import paths
  File "/home/pi/.local/lib/python3.7/site-packages/imutils/__init__.py", line 8, in <module>
    from .convenience import translate
  File "/home/pi/.local/lib/python3.7/site-packages/imutils/convenience.py", line 6, in <module>
    import cv2
  File "/usr/local/lib/python3.7/dist-packages/cv2/__init__.py", line 89, in <module>
    bootstrap()
  File "/usr/local/lib/python3.7/dist-packages/cv2/__init__.py", line 79, in bootstrap
    import cv2
ImportError: libtesseract.so.4: cannot open shared object file: No such file or directory

**Comment by nischi** [comment]
This seems something is not correct installed. or maybe wrong python version?
